In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

# 1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type

In [2]:
arr = np.arange(0,6)
print(arr.dtype)
print("\n\n",type(arr))

int32


 <class 'numpy.ndarray'>


# 2.Given a NumPy array 'arr', check if its data type is float64

In [3]:
arr = np.array([1.5 , 2.6 , 3.7])
print(arr.dtype)

float64


# 3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers

In [4]:
arr = np.array([3 + 2j , 1+14j , 2 + 7j])

print(arr.dtype , end = "\n\n")

print(arr)

complex128

[3. +2.j 1.+14.j 2. +7.j]


# 4.Convert an existing NumPy array 'arr' of integers to float32 data type

In [5]:
arr = np.arange(10)

print("Array data type before: ",arr.dtype)

arr = arr.astype(float)

print("Array data type after converting: ", arr.dtype)

Array data type before:  int32
Array data type after converting:  float64


# 5.Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [6]:
arr = np.array([1.123456789, 2.987654321, 3.1415926535] , dtype = np.float64)

arr = arr.astype(np.float32)

print(arr.dtype)

print(arr)

float32
[1.1234568 2.9876542 3.1415927]


# 6.Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype

In [7]:
def fun(arr):
    return arr.shape , arr.size , arr.dtype


# input_user = input("Enter the array elements separated by spaces: ")
# arr = np.array([float(x) for x in input_user.split()])

# arr = np.array([float(x) for x in input("Enter elements with spaces ").split()])

arr = np.array([[1,2,3] , [4 ,5 ,6]] ,dtype = np.float64)

k = fun(arr)

print(f"Shape: {k[0]} \nSize: {k[1]} \nData type: {k[2]}")

Shape: (2, 3) 
Size: 6 
Data type: float64


# 7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [8]:
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1,2,3] , [4 ,5 ,6]] ,dtype = np.float64)

array_dimension(arr)

2

# 8.Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes

In [9]:
def item_size_info(arr):
    return arr.itemsize , arr.nbytes

arr = np.array([[1,2,3] , [4 ,5 ,6]] ,dtype = np.int32)

item_size_info(arr)

#itemsize ante datatype oka size

(4, 24)

# 9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [10]:
def array_strides(arr):
    return arr.strides


arr = np.array([[1,2,3] , [4,5,6]] , dtype = np.int16)

array_strides(arr)

#the stride of an array 
#(also referred to as increment, pitch or step size) is the number of locations 
#in memory between beginnings of successive array elements, measured in bytes or in units of the size of the array's elements

(6, 2)

# 10.Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array

In [11]:
def shape_stride_relationship(arr):
    return arr.shape , arr.strides

arr = np.array([[1,2,3] , [4,5,6]] , dtype = np.int16)

k = shape_stride_relationship(arr)

print(f"The shape is: {k[0]}\nThe Strides is {k[1]}")

The shape is: (2, 3)
The Strides is (6, 2)


# 11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elementss

In [12]:
def create_zeros_array(n):
    return np.zeros(n)


create_zeros_array((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols``

In [13]:
def create_ones_matrix(rows , cols):
    return np.ones((rows , cols))


create_ones_matrix(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 13.Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`p`

In [14]:
def generate_range_array(start , stop , step):
    return np.arange(start , stop , step)


generate_range_array(4 , 24 , 3)

array([ 4,  7, 10, 13, 16, 19, 22])

# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive)

In [15]:
def generate_linear_space(start , stop , num):
    return np.linspace(start , stop , num)

generate_linear_space(4 , 5 , 20)

array([4.        , 4.05263158, 4.10526316, 4.15789474, 4.21052632,
       4.26315789, 4.31578947, 4.36842105, 4.42105263, 4.47368421,
       4.52631579, 4.57894737, 4.63157895, 4.68421053, 4.73684211,
       4.78947368, 4.84210526, 4.89473684, 4.94736842, 5.        ])

# 15.  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`e

In [16]:
def create_identity_matrix(n):
    return np.eye(n)

create_identity_matrix(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 16.Write a function that takes a Python list and converts it into a NumPy array

In [17]:
def fun(lis):
    return np.array(lis)


fun([1,2,3,4,5])

array([1, 2, 3, 4, 5])

# 17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data

In [18]:
arr = np.array([1, 2, 3, 4])

view_arr = arr.view()


print("Original array:", arr)
print("View array:", view_arr)

view_arr[1] = 10

print("Modified original array:", arr)
print("Modified view array:", view_arr)

#if we modify the viw array it would affect in orginal too

Original array: [1 2 3 4]
View array: [1 2 3 4]
Modified original array: [ 1 10  3  4]
Modified view array: [ 1 10  3  4]


# 18.Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [19]:
def fun(arr1 , arr2 , ax):
    return np.concatenate((arr1 , arr2) , axis = ax)


arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]

fun(arr1 , arr2 , 0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy`

In [20]:
arr1 = np.random.randint(1,5 , size = (3,3))
arr2 = np.random.randint(1,5 , size = (3,4))

np.concatenate((arr1 , arr2) , axis = 1)

array([[1, 3, 3, 3, 3, 4, 4],
       [4, 1, 3, 2, 2, 4, 4],
       [1, 1, 3, 1, 1, 2, 3]])

# 20.Write a function that vertically stacks multiple NumPy arrays given as a list

In [21]:
def ver(arrys):
    return np.vstack(arrys)


arr1 = np.random.randint(1, 5, size=(2, 3))
arr2 = np.random.randint(1, 5, size=(3, 3))
arr3 = np.random.randint(1, 5, size=(1, 3))


ver([arr1,arr2,arr3]) #pass as list form bcs we are using args na

array([[3, 4, 2],
       [4, 4, 3],
       [2, 3, 2],
       [1, 1, 4],
       [2, 1, 1],
       [2, 1, 2]])

# 21.Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size

In [22]:
def generate_range_array(start , stop , step):
    return np.arange(start , stop +1 , step)


generate_range_array(4 , 24 , 2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive)

In [23]:
def generate_linear_space(start , stop , num):
    return np.linspace(start , stop , num)

generate_linear_space(4 , 5 , 20)

array([4.        , 4.05263158, 4.10526316, 4.15789474, 4.21052632,
       4.26315789, 4.31578947, 4.36842105, 4.42105263, 4.47368421,
       4.52631579, 4.57894737, 4.63157895, 4.68421053, 4.73684211,
       4.78947368, 4.84210526, 4.89473684, 4.94736842, 5.        ])

# 23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive))

In [24]:
def logarr():
    return np.logspace(1 , 1000+1, num =  5 ,base=2)

k = logarr()
print(k)

[2.00000000e+000 3.61850279e+075 6.54678122e+150 1.18447730e+226
 2.14301721e+301]


# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 1000

In [25]:
arr = np.random.randint(1 , 1000 , size = (5,3))

pd.DataFrame(arr)

0    1    2
0  179  656  727
1  438  342  270
2  607  763  376
3  976  366  302
4  282  761  736

# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFramee

In [26]:
def rep_with_zero(df , column):


    df[column] = np.where(df[column] < 0 , 0 , df[column])
    return df


data = {'A': [1, -2, 3, -4, 5], 'B': [10, -20, 30, -40, 50]}
df = pd.DataFrame(data)


rep_with_zero(df, 'A')

A   B
0  1  10
1  0 -20
2  3  30
3  0 -40
4  5  50

# 26.Access the 3rd element from the given NumPy array

In [27]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

# 27.Retrieve the element at index (1, 2) from the 2D NumPy array

In [28]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[1][2]

6

# 28.Using boolean indexing, extract elements greater than 5 from the given NumPy array

In [29]:
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

# 29.Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

# 30.Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array

In [31]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr = arr_2d[0:2 , 1:]
arr

array([[2, 3],
       [5, 6]])

# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array

In [32]:
def exe(arr ,indes):
    return arr[indes[: ,0] , indes[:,1]]


arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

indices = np.array([[0, 2],  # Element at row 0, column 2
                    [1, 0],  # Element at row 1, column 0
                    [2, 1]]) # Element at row 2, column 1

exe(arr, indices)

array([30, 40, 80])

# 32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexingg

In [33]:
def pip(arr,threshold):
    return arr[arr > threshold]

threshold = 5

pip(np.array([3, 8, 2, 10, 5, 7]) , threshold)

array([ 8, 10,  7])

# 33.Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimensionn

In [34]:
def exe(arr,r,c,d):
    return arr[r,c,d]

arr = np.array([[[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]],
                 
                [[11, 21, 31],
                 [41, 51, 61],
                 [71, 81, 91]],
                 
                [[12, 22, 32],
                 [42, 52, 62],
                 [72, 82, 92]]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 0, 1])
depth_indices = np.array([1, 2, 0])

exe(arr, row_indices, col_indices, depth_indices)


array([80, 31, 42])

# 34.Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexingg

In [35]:
def con(arr ,c1 ,c2):
    return arr[c1(arr) & c2(arr)]

arr = np.array([10, 15, 20, 25, 30, 35, 40])

condition1 = lambda x: x > 15
condition2 = lambda x: x < 35

con(arr, condition1, condition2)

array([20, 25, 30])

# 35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrayss

In [36]:
def exe(arr,r,c):
    return arr[r,c]

arr = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 
                 [11, 21, 31],
                 [41, 51, 61],
                 [71, 81, 91],
                 
                 [12, 22, 32],
                 [42, 52, 62],
                 [72, 82, 92]])

row_indices = np.array([0, 1])
col_indices = np.array([2, 0])

exe(arr, row_indices, col_indices)

array([30, 40])

# 36.Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting

In [37]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# 37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcastingg

In [38]:
arr1 = np.array([[2, 4, 6]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)


arr1_broadcasted = np.reshape(arr1, (3, 1))

# arr1_broadcasted*arr2

arr2 * arr1_broadcasted

array([[ 2,  4,  6,  8],
       [20, 24, 28, 32],
       [54, 60, 66, 72]])

# 38.Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcastingg

In [39]:
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12],
                 [13, 14, 15]])  # Shape (4, 3)

arr2 + arr1

array([[ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15],
       [14, 16, 18]])

# 39.Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcastingg

In [40]:
arr1 = np.random.randint(1,5,size = (3,1))
arr2 = np.array([[1, 2, 3]])

arr1 + arr2

array([[3, 4, 5],
       [2, 3, 4],
       [5, 6, 7]])

# 40.Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibilityy

In [41]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[1, 2],
                 [3, 4]])  # Shape (2, 2)

arr2_reshaped = arr2[:, np.newaxis, :]

arr1_expanded = arr1[:, :, np.newaxis]

arr1_expanded * arr2_reshaped

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[12, 16],
        [15, 20],
        [18, 24]]])

# 41.Calculate column wise mean for the given array

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr , axis = 0)

array([2.5, 3.5, 4.5])

# 42.Find maximum value in each row of the given array

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr , axis = 1)

array([3, 6])

# 43.For the given array, find indices of maximum value in each column

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.argmax(arr , axis = 0)

array([1, 1, 1], dtype=int64)

# 44.For the given array, apply custom function to calculate moving sum along rows

In [45]:
def cum(row):
    c_s = 0
    res = []
    for i in row:
        c_s += i
        res.append(c_s)
    return res

arr = np.array([[1, 2, 3], [4, 5, 6]])
res = np.apply_along_axis(cum, 1, arr)

res

array([[ 1,  3,  6],
       [ 4,  9, 15]])

# 45.In the given array, check if all elements in each column are even

In [46]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
print(arr%2 == 0)

[[ True  True  True]
 [False False False]]


# 46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrixx

In [47]:
original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = np.reshape(original_array , (2,3))

print(reshaped_array)

[[1 2 3]
 [4 5 6]]


# 47.Create a function that takes a matrix as input and returns the flattened array

In [48]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

input_matrix.flatten()

array([1, 2, 3, 4, 5, 6])

# 48.Write a function that concatenates two given arrays along a specified axis

In [49]:
def conca(arr1 , arr2 , ax):
    return np.concatenate((arr1 , arr2) , axis = ax)
    
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


conca(array1 , array2 , 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# 49.Create a function that splits an array into multiple sub-arrays along a specified axis

In [50]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(original_array , 3 , axis = 0) #That number is to split how many arrays we want to

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

# 50.Write a function that inserts and then deletes elements from a given array at specified indices

In [51]:
def pip(arr,indices_to_insert,values_to_insert,indices_to_delete):
    mod_arr = arr.copy()
    for index , value in zip(indices_to_insert , values_to_insert):
        mod_arr = np.insert(mod_arr , index , value)


    mod_arr = np.delete(mod_arr , indices_to_delete)

    return mod_arr





    
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


pip(original_array , indices_to_insert , values_to_insert , indices_to_delete)

array([ 1, 10, 11,  4,  5])

# 51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.Perform element-wise addition between `arr1` and `arr2``

In [52]:
arr1 = np.random.randint(0,100 ,10)
arr2 = np.arange(1 ,11)

arr1 + arr2

array([28, 38, 92, 46, 58, 49, 36, 69, 28, 94])

# 52.Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wisee

In [53]:
arr1 = np.arange(10 , 0 , -1)

arr2 = np.arange(1,11)

arr2 - arr1

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9])

# 53.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.Perform element-wise multiplication between `arr1` and `arr2`.

In [54]:
arr1 = np.random.randint(1,100,10)
arr2 = np.random.randint(1,6)

arr1 * arr2

array([490, 310, 125, 240, 385, 420, 395, 295,  90, 275])

# 54.Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2``

In [55]:
arr1 = np.arange(2, 11 , 2)
arr2 = np.arange(1 , 6)

arr1 / arr2

array([2., 2., 2., 2., 2.])

# 55.Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wisee

In [56]:
arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)

arr1 ** arr2

array([ 1, 16, 27, 16,  5])

# 56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings

In [57]:
def fun(arr , ss):
    count = 0
    for str in arr:
        count += str.count(ss)
    return count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
fun(arr , 'hello')

3

# 57. Write a function that extracts uppercase characters from a NumPy array of strings])

In [58]:
def exe_upp(arr):
    res = []
    for str in arr:
        uppp_chrs = ''.join([char for char in str if char.isupper()])
        res.append(uppp_chrs)
    return np.array(res)

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
exe_upp(arr)

array(['H', 'W', 'OAI', 'GPT'], dtype='<U3')

# 58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string

In [59]:
def rep(arr , old , new):
    return np.char.replace(arr , old ,new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

rep(arr , 'apple' , 'orange')

array(['orange', 'banana', 'grape', 'pineorange'], dtype='<U10')

# 59.Write a function that concatenates strings in a NumPy array element-wise

In [60]:
def conca(arr1 , arr2):
    return np.char.add(arr1 , arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

conca(arr1 , arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

# 60.Write a function that finds the length of the longest string in a NumPy array.])

In [61]:
def ll(arr):
    len_arr = np.array([len(s) for s in arr])



    return np.max(len_arr)


arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

ll(arr)

9

# 61.Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functionss

In [62]:
data = np.random.randint(1,1001,100)


mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 525.92
Median: 557.0
Variance: 72946.81360000001
Standard Deviation: 270.0866779387684


# 62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the datasett

In [63]:
arr = np.random.randint(1, 100 , 50)
np.percentile(arr , [0.25,0.75])

array([1., 1.])

# 63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` functionn

In [64]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

np.corrcoef(x , y)

array([[1.        , 0.77459667],
       [0.77459667, 1.        ]])

# 64.Create two matrices and perform matrix multiplication using NumPy's `dot` function

In [65]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])


np.dot(matrix1 , matrix2)

array([[19, 22],
       [43, 50]])

# 65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiless

In [66]:
arr = np.random.randint(10,1001,50)

print(np.percentile(arr , [0.10 ,0.50 , 0.90]))

print(np.quantile(arr , [.25 , .75]))

[35.441 37.205 38.969]
[231.   719.75]


# 66.Create a NumPy array of integers and find the index of a specific element

In [70]:
#arr = np.random.randint(10,1001,50)

print(np.where(arr == 667)[0][0])

45


# 67.Generate a random NumPy array and sort it in ascending order

In [71]:
arr = np.random.randint(100,1001,10)

print("Array before sorting \n\n" , arr)

copy = np.sort(arr)

print("\nArray after sorting \n\n" , copy)

Array before sorting 

 [931 538 964 521 518 485 765 125 608 359]

Array after sorting 

 [125 359 485 518 521 538 608 765 931 964]


# 68.Filter elements >20  in the given NumPy array

In [72]:
arr = np.array([12, 25, 6, 42, 8, 30])

arr[arr>20]

array([25, 42, 30])

# 69.Filter elements which are divisible by 3 from a given NumPy array

In [73]:
arr = np.array([1, 5, 8, 12, 15])

arr[arr%3 == 0]

array([12, 15])

# 70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array

In [74]:
arr = np.array([10, 20, 30, 40, 50])

arr[(arr>= 20) & (arr<= 40)]

array([20, 30, 40])

# 71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder

In [75]:
arr = np.array([1, 2, 3])


arr.dtype.byteorder #Ante each ki enni bytes unayo anesi

'='

# 72.For the given NumPy array, perform byte swapping in place using `byteswap()`

In [76]:
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap()

array([16777216, 33554432, 50331648])

# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()``

In [77]:
arr = np.array([1, 2, 3], dtype=np.int32)

arr.newbyteorder()

array([16777216, 33554432, 50331648])

# 74.For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()``

In [78]:
arr = np.array([1, 2, 3], dtype=np.int32)

import sys

system_byte_order = sys.byteorder

# Swap byte order if necessary
if system_byte_order == 'little':
    new_arr = arr.astype(arr.dtype.newbyteorder('>'))
else:
    new_arr = arr.astype(arr.dtype.newbyteorder('<'))

print("Original array:", arr)
print("New array with conditionally swapped byte order:", new_arr)

Original array: [1 2 3]
New array with conditionally swapped byte order: [1 2 3]


# 75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`

In [79]:
arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder != sys.byteorder:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")

Byte swapping is necessary.


# 76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1``

In [80]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])


copy_arr = arr1.copy()


copy_arr[0] = 100


print("arr1:", arr1)
print("copy_arr:", copy_arr)

arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


# 77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [81]:
matrix = np.random.randint(0, 10, (3, 3))


view_slice = matrix[0:2, 1:3]


view_slice[0, 0] = 99


print("Original matrix:")
print(matrix)

Original matrix:
[[ 3 99  9]
 [ 4  2  1]
 [ 2  7  7]]


# 78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`a

In [82]:
array_a = np.arange(1, 13).reshape(4, 3)


view_b = array_a[1:3, 1:3]


view_b += 5


print("Original array_a:\n")
print(array_a)

Original array_a:

[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


# 79.Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`y`

In [83]:
orig_array = np.arange(1, 9).reshape(2, 4)


reshaped_view = orig_array.reshape(4, 2)


reshaped_view[0, 0] = 100


print("Original array:\n")
print(orig_array)

Original array:

[[100   2   3   4]
 [  5   6   7   8]]


# 80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data``

In [84]:
data = np.random.randint(0, 10, (3, 4))


data_copy = data[data > 5].copy()


data_copy[0] = 100


print("Original data:\n")
print(data)

print("\n\nData copy:\n")
print(data_copy)

Original data:

[[0 7 5 6]
 [3 3 4 7]
 [5 8 9 2]]


Data copy:

[100   6   7   8   9]


# 81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between themm

In [85]:
A = np.random.randint(1, 10, (3 , 4))
B = np.random.randint(1, 10, (3 ,4))


sum_matrix = A + B
difference_matrix = A - B


print("Sum of A and B:\n")
print(sum_matrix)

print("\n\n\nDifference of A and B:\n")
print(difference_matrix)

Sum of A and B:

[[12  8 11  4]
 [10 13 11  8]
 [10 11  4 10]]



Difference of A and B:

[[ 2  2 -5  0]
 [-2 -3 -7 -4]
 [-8 -1  2 -4]]


# 82.Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [86]:
C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))


np.dot(C, D)

array([[27, 44, 46, 51],
       [27, 25, 29, 30],
       [30, 32, 36, 38]])

# 83.Create a matrix `E` and find its transpose

In [87]:
E = np.random.randint(1, 10, (3, 4))

print("Matrix E:\n")
print(E)

print("\n\nTranspose of E:\n")
print(E.T)

Matrix E:

[[1 3 2 9]
 [8 9 5 7]
 [2 9 3 1]]


Transpose of E:

[[1 8 2]
 [3 9 9]
 [2 5 3]
 [9 7 1]]


# 84.Generate a square matrix `F` and compute its determinant

In [88]:
F = np.random.randint(1, 10, (4, 4))


determinant = np.linalg.det(F)

print("Matrix F:\n")
print(F)

print("\n\nDeterminant of F:\n")
print(determinant)

Matrix F:

[[3 4 1 8]
 [9 8 8 4]
 [1 2 4 2]
 [6 6 1 3]]


Determinant of F:

330.0000000000002


# 85.Create a square matrix `G` and find its inverse

In [89]:
G = np.random.randint(1, 10, (4, 4))


inverse_G = np.linalg.inv(G)

print("Matrix G:\n")
print(G)

print("\n\nInverse of G:\n")
print(inverse_G)

Matrix G:

[[1 5 2 5]
 [2 9 4 4]
 [5 6 3 7]
 [1 3 3 2]]


Inverse of G:

[[-0.39622642  0.0754717   0.27044025 -0.10691824]
 [-0.03773585  0.24528302 -0.03773585 -0.26415094]
 [-0.05660377 -0.13207547 -0.05660377  0.60377358]
 [ 0.33962264 -0.20754717  0.00628931  0.04402516]]
